# Generated by Django 2.0.3 on 2019-03-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_group', models.CharField(default=None, max_length=64)),
                ('data_size', models.CharField(default=None, max_length=64)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('extras', models.CharField(default=None, max_length=64)),
                ('extras_price', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('name', models.CharField(default=None, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('toppings', models.CharField(default=None, max_length=64)),
                ('user', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
