# Generated by Django 2.0.3 on 2019-03-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190320_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='date_ordered',
        ),
    ]
