# Generated by Django 2.0.3 on 2019-02-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190223_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppings',
        ),
    ]
