# Generated by Django 2.0.3 on 2019-03-20 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderhistory_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
