# Generated by Django 2.0.3 on 2019-02-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_sublg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubLg',
            new_name='SubLarge',
        ),
    ]
