# Generated by Django 2.0.3 on 2019-02-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190224_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
                ('item', models.CharField(max_length=64)),
                ('price_sm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_lg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='SubLarge',
        ),
    ]
