# Generated by Django 2.0.3 on 2019-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190226_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('menu_item_id', models.IntegerField()),
                ('menu_item', models.ManyToManyField(blank=True, related_name='shopping_cart', to='orders.MenuItem')),
            ],
        ),
    ]
