# Generated by Django 2.0.3 on 2019-03-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_customer'),
        ('orders', '0009_shoppingcart'),
    ]

    operations = [
    ]
