# Generated by Django 2.0.3 on 2019-03-04 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190304_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='price',
            new_name='price_lg',
        ),
        migrations.AddField(
            model_name='extra',
            name='price_sm',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
