# Generated by Django 2.0.3 on 2019-03-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190304_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
