# Generated by Django 2.0.3 on 2019-03-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delete_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('price_sm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_lg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
