# Generated by Django 2.0.3 on 2019-03-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.CharField(max_length=64),
            preserve_default=False,
        ),
    ]
