# Generated by Django 2.0.3 on 2019-03-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_menuitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
    ]
